data_dir: data
results_dir: results
users:
  - 02A8
  - 402E
  - 52EA
  - 682A
  - 9FE9
  - F176
dificulties:
  - easy
  - medium
  - hard
rooms:
  - TV Room
  - Therapy Room
  - Gym
  - Terrace
  - Room
colors:
  TV Room:
    - 255
    - 0
    - 0
  Living Room:
    - 0
    - 255
    - 0
  Therapy Room:
    - 0
    - 0
    - 255
  Gym:
    - 255
    - 255
    - 0
  Corridor:
    - 128
    - 0
    - 128
  Terrace:
    - 0
    - 255
    - 255
  Dinning Room:
    - 255
    - 165
    - 0
  Room:
    - 144
    - 238
    - 144
params:
  Room:
    length_range:
      - 3
      - 100
    R: 1
    C: 30
    G: 8
    L: 1
    epsilon: 0.5
    fusion_distance: 0.001
  other:
    length_range:
      - 3
      - 100
    R: 3
    C: 6
    G: 8
    L: 1
    epsilon: 0.5
    fusion_distance: 0.001
intervals_of_interest:
  9FE9:
    -
      duration_time: 75
      start: 10:15
      end: 11:29
    -
      duration_time: 90
      start: 11:30
      end: 13:00
    -
      duration_time: 90
      start: 13:30
      end: 14:59
    -
      duration_time: 75
      start: 15:00
      end: 16:15
    -
      duration_time: 75
      start: 16:45
      end: 17:59
    -
      duration_time: 90
      start: 18:00
      end: 19:30
N_weekdays_on_month:
  Monday: 4
  Tuesday: 4
  Wednesday: 5
  Thursday: 5
  Friday: 5
  Saturday: 4
  Sunday: 4